name: Send emails daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MAX_PAPER_NUM: ${{ secrets.MAX_PAPER_NUM }}
          USE_LLM_API: ${{ secrets.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE }}
        run: |
          MAX_RETRIES=3
          WAIT_SECONDS=60
          
          count=0
          until uv run main.py; do
            exit_code=$?
            count=$((count + 1))
            if [ $count -ge $MAX_RETRIES ]; then
              echo "Script failed after $count attempts."
              exit $exit_code
            fi
            echo "Attempt $count failed! Retrying in $WAIT_SECONDS seconds..."
            sleep $WAIT_SECONDS
          done
          echo "Script executed successfully."
